title: rafael1138L cuentos, artículos y plástico
description: cuentos, artículos y plástico
image: "https://i.imgur.com/e8z3XdH.jpg"
</html>
author: rafael1138
github: https://github.com/rafael1138
about: rafael Martinez, abogado veneco/gringo, especialista en derecho internacional, informático y bancario. analista de impuestos internacionales. coleccionista de star wars. horrendo escritor de cuentos, artículos de opinión y papeles académicos.
disqus_shortname: 
google_analytics: 

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/rafael1138"

share:
  twitter_username: rafaelmmv
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: Acerca de Mi
      url: /acerca/  
 #   - text: My Projects
 #     url: /projects/
    - text: Categories-Categorías
      url: https://rafael1138.github.io/category/academics
    - text: XML Feed
      url: /feed.xml
    
url: "https://rafael1138.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
